version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: app.dock
    ports:
      - 5000:5000
    container_name: app
  web:
    build: 
      context: .
      dockerfile: web.dock
    container_name: web
    ports:
        - 80:80
    links:
        - app
